add --test-requires option to ext-files

diff --git a/ext-files b/ext-files
--- a/ext-files
+++ b/ext-files
@@ -18,6 +18,10 @@
 #    --presence
 #          also includes the status of each external file, whether it
 #          could be found (and read) or not.
+#    --test-requires=depfile
+#          don’t produce any output, but return a success/failure exit
+#          status if blendfile does/does not have depfile as a dependency
+#          respectively. Incompatible with the --full or --presence options.
 #
 # Copyright 2015-2016 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
 # Licensed under CC-BY-SA <http://creativecommons.org/licenses/by-sa/4.0/>.
@@ -26,6 +30,7 @@
 blender=blender
 full_json=
 presence=
+test_requires=
 for ((;;)); do
     if [ "${1:0:2}" != "--" ]; then
         break
@@ -44,11 +49,19 @@ for ((;;)); do
         full_json=1
     elif [ "$opt" = "presence" ]; then
         presence=1
+    elif [ "$opt" = "test-requires" ]; then
+        test_requires="$val"
     else
         echo "$0: bad option $opt" 1>&2
         exit 3
     fi
 done
+if [ -n "$test_requires" ]; then
+    if [ "$full_json" -o "$presence" ]; then
+        echo "$0: --test_requires incompatible with --full or --presence" 1>&2
+        exit 3
+    fi
+fi
 if [ -z "$(type -p "$blender")" ]; then
     echo "$0: no such executable “$blender”" 1>&2
     exit 3
@@ -60,6 +73,7 @@ fi
 export RENDER_blendfile="$1"
 export RENDER_full_json="$full_json"
 export RENDER_presence="$presence"
+export RENDER_test_requires="$test_requires"
 
 exec "$blender" 5>&1 1>/dev/null -b -P <(cat <<'EOD'
 import sys
@@ -67,17 +81,28 @@ import os
 import json
 import bpy
 
-def path_ok(path) :
-    # checks that the file at path exists and is accessible. Requires
-    # parent_dir to be defined as the parent directory of the .blend
-    # file for interpreting relative paths.
+def expand_path(path, allow_curdir_relative) :
+    # normalizes path to be a full pathname. Requires parent_dir to be
+    # defined as the parent directory of the .blend file for
+    # interpreting relative paths.
     if path.startswith("//") :
         # Blender convention for path relative to .blend file
         path = os.path.join(parent_dir, path[2:])
     elif not path.startswith("/") :
-        # not expecting a path relative to anything else!
-        path = None
+        if allow_curdir_relative :
+            path = os.path.abspath(path)
+        else :
+            # not expecting a path relative to anything else!
+            path = None
+        #end if
     #end if
+    return \
+        path
+#end expand_path
+
+def path_ok(path) :
+    # checks that the file at path exists and is accessible.
+    path = expand_path(path, False)
     return \
         (
             path != None
@@ -96,14 +121,23 @@ blendfile = os.getenv("RENDER_blendfile")
 bpy.ops.wm.open_mainfile(filepath = blendfile)
 full_json = os.getenv("RENDER_full_json", "") != ""
 presence = os.getenv("RENDER_presence", "") != ""
+test_requires = os.getenv("RENDER_test_requires")
+if test_requires == "" :
+    test_requires = None
+#end if
 
 if full_json :
     out.write("{")
     first_cat = True
 #end if
-if presence :
-    parent_dir = os.path.split(bpy.data.filepath)[0]
+if presence or test_requires != None :
+    parent_dir = os.path.split(os.path.abspath(bpy.data.filepath))[0]
 #end if
+found = False
+if test_requires != None :
+    test_requires = expand_path(test_requires, True)
+#end if
+exit_status = 0
 for \
     category, match, mismatch, extra \
 in \
@@ -162,14 +196,22 @@ in \
                     #end if
                 #end for
                 out.write("\n            }")
-            else :
+            elif test_requires == None :
                 if presence :
                     out.write("%s: " % ("missing", "present")[path_ok(item.filepath)])
                 #end if
                 out.write(item.filepath + "\n")
+            else :
+                if expand_path(item.filepath, False) == test_requires :
+                    found = True
+                    break
+                #end if
             #end if
         #end if
     #end for
+    if found :
+        break
+    #end if
     if full_json :
         out.write("\n        ]")
     #end if
@@ -177,6 +219,11 @@ in \
 if full_json :
     out.write("\n}\n")
 #end if
-out.flush()
+if test_requires != None :
+    exit_status = 1 - int(found)
+else :
+    out.flush()
+#end if
+sys.exit(exit_status)
 EOD
 )
