add --test-missing option to ext-files

diff --git a/ext-files b/ext-files
--- a/ext-files
+++ b/ext-files
@@ -18,18 +18,25 @@
 #    --presence
 #          also includes the status of each external file, whether it
 #          could be found (and read) or not.
+#    --test-missing
+#          don’t produce any output, but return a success/failure exit
+#          status if blendfile does/does not have any missing dependencies
+#          respectively. Incompatible with the --full, --presence or test-missing
+#          options.
 #    --test-requires=depfile
 #          don’t produce any output, but return a success/failure exit
 #          status if blendfile does/does not have depfile as a dependency
-#          respectively. Incompatible with the --full or --presence options.
+#          respectively. Incompatible with the --full, --presence or test-requires
+#          options.
 #
-# Copyright 2015-2016 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
+# Copyright 2015-2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
 # Licensed under CC-BY-SA <http://creativecommons.org/licenses/by-sa/4.0/>.
 #-
 
 blender=blender
 full_json=
 presence=
+test_missing=
 test_requires=
 for ((;;)); do
     if [ "${1:0:2}" != "--" ]; then
@@ -49,6 +56,8 @@ for ((;;)); do
         full_json=1
     elif [ "$opt" = "presence" ]; then
         presence=1
+    elif [ "$opt" = "test-missing" ]; then
+        test_missing=1
     elif [ "$opt" = "test-requires" ]; then
         test_requires="$val"
     else
@@ -56,11 +65,13 @@ for ((;;)); do
         exit 3
     fi
 done
-if [ -n "$test_requires" ]; then
-    if [ "$full_json" -o "$presence" ]; then
-        echo "$0: --test_requires incompatible with --full or --presence" 1>&2
-        exit 3
-    fi
+incompat=0
+for v in full_json presence test_missing test_requires; do
+    incompat=$(($incompat + $(if [ -n "${!v}" ]; then echo -n 1; else echo -n 0; fi)))
+done
+if [ $incompat -gt 1 ]; then
+    echo "$0: only one of --full, --presence, --test-missing or --test_requires can be specified" 1>&2
+    exit 3
 fi
 if [ -z "$(type -p "$blender")" ]; then
     echo "$0: no such executable “$blender”" 1>&2
@@ -73,6 +84,7 @@ fi
 export RENDER_blendfile="$1"
 export RENDER_full_json="$full_json"
 export RENDER_presence="$presence"
+export RENDER_test_missing="$test_missing"
 export RENDER_test_requires="$test_requires"
 
 exec "$blender" -noaudio 5>&1 1>/dev/null -b -P <(cat <<'EOD'
@@ -121,6 +133,7 @@ blendfile = os.getenv("RENDER_blendfile")
 bpy.ops.wm.open_mainfile(filepath = blendfile)
 full_json = os.getenv("RENDER_full_json", "") != ""
 presence = os.getenv("RENDER_presence", "") != ""
+test_missing = os.getenv("RENDER_test_missing", "") != ""
 test_requires = os.getenv("RENDER_test_requires")
 if test_requires == "" :
     test_requires = None
@@ -130,10 +143,13 @@ if full_json :
     out.write("{")
     first_cat = True
 #end if
-if presence or test_requires != None :
+if presence or test_missing or test_requires != None :
     parent_dir = os.path.split(os.path.abspath(bpy.data.filepath))[0]
 #end if
 found = False
+if test_missing :
+    missing = 0
+#end if
 if test_requires != None :
     test_requires = expand_path(test_requires, True)
 #end if
@@ -203,10 +219,14 @@ in \
                 #end for
                 out.write("\n            }")
             elif test_requires == None :
-                if presence :
-                    out.write("%s: " % ("missing", "present")[path_ok(item.filepath)])
+                if test_missing :
+                    missing += int(not path_ok(item.filepath))
+                else :
+                    if presence :
+                        out.write("%s: " % ("missing", "present")[path_ok(item.filepath)])
+                    #end if
+                    out.write(item.filepath + "\n")
                 #end if
-                out.write(item.filepath + "\n")
             else :
                 if expand_path(item.filepath, False) == test_requires :
                     found = True
@@ -227,6 +247,8 @@ if full_json :
 #end if
 if test_requires != None :
     exit_status = 1 - int(found)
+elif test_missing :
+    exit_status = (0, 1)[missing != 0]
 else :
     out.flush()
 #end if
